In [2]:
import torch

In [3]:
randint=torch.randint(-100,100,(20,))
print(randint)

tensor([-29,  56,  27, -39, -56,  -3, -72,  77, -49, -16,  12, -24,  83,  55,
         31,  88,  30, -76, -67, -78])


In [4]:
tensor=torch.tensor([[0.1,0.2,0.3],[0.1,0.2,0.3]])
print(tensor)

tensor([[0.1000, 0.2000, 0.3000],
        [0.1000, 0.2000, 0.3000]])


In [5]:
zeros=torch.zeros(2,3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
ones=torch.ones(4,5)
print(ones)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [7]:
print(torch.arange(5))

tensor([0, 1, 2, 3, 4])


In [8]:
print(torch.linspace(3,10,steps=5))

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])


In [9]:
print(torch.eye(5))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [10]:
device='cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [11]:
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [12]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [13]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [14]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [15]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [16]:
input = torch.zeros(2, 3, 4)
out1 = input.transpose(0, 1)
out2 = input.transpose(-2,-1)
print(out1.shape)
print(out2.shape)

torch.Size([3, 2, 4])
torch.Size([2, 4, 3])


In [17]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([5.0135, 2.2476, 5.4155], grad_fn=<SqueezeBackward4>)


In [19]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [20]:
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[-1.1626, -0.4576, -1.4716, -0.8250, -0.9402,  0.7105],
        [ 1.2241,  0.2255,  2.4098, -0.4475,  0.6994,  0.4754],
        [ 0.0257,  0.5413, -1.2413,  1.0173, -0.1692, -1.0505],
        [-1.4922, -1.3103, -0.6779, -1.4643,  1.0108,  0.0746]],
       grad_fn=<EmbeddingBackward0>)


In [21]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
# print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [22]:
int_64 = torch.randint(1, (3, 2)).float()
#type int64
float_32 = torch.rand(2,3)
#type float32
# print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [23]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
# print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [24]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
# print(input)
print(output[:, -1, :])

tensor([[0.6446, 0.9615, 0.7839, 0.6880, 0.3093, 0.7447, 0.7553, 0.4562, 0.6875,
         0.5770],
        [0.0561, 0.4967, 0.2715, 0.1403, 0.7134, 0.8813, 0.9516, 0.3809, 0.4099,
         0.4651],
        [0.7678, 0.7613, 0.7476, 0.8567, 0.9680, 0.9766, 0.4500, 0.5124, 0.7085,
         0.6664],
        [0.0578, 0.4734, 0.7568, 0.4053, 0.9141, 0.5462, 0.8319, 0.9181, 0.6684,
         0.7898],
        [0.9670, 0.1410, 0.8129, 0.6290, 0.1521, 0.6785, 0.7747, 0.7662, 0.0623,
         0.0568],
        [0.7197, 0.0552, 0.3780, 0.6302, 0.5321, 0.5969, 0.8539, 0.6681, 0.9476,
         0.7464],
        [0.6213, 0.9331, 0.9898, 0.6345, 0.8104, 0.2890, 0.6207, 0.0654, 0.0202,
         0.3591],
        [0.8250, 0.7129, 0.3399, 0.4637, 0.1423, 0.8818, 0.0198, 0.2514, 0.5438,
         0.3619],
        [0.4441, 0.6162, 0.5902, 0.7614, 0.9555, 0.3391, 0.2544, 0.8159, 0.4732,
         0.4039],
        [0.6178, 0.5403, 0.8222, 0.4796, 0.0145, 0.1856, 0.1258, 0.2267, 0.2421,
         0.1370],
        [0

IndexError: too many indices for tensor of dimension 2

In [25]:
x = torch.tensor([10], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([1.])
